### ISSUE TITLE
swithed background image

### ISSUE THREAD

**Issue by az4aaz** [Luvey35/Site_Personnelle#2]
Hi ! love your website <3
I just found out that in mobile mode, the background images of the KOH-frais project and yams are switched.
![pic-selected-240602-2316-04](https://github.com/LucasVaugrente/Site-Personnel/assets/42306217/d18dd356-61b9-4638-917f-a160fc50e9f7)
I'm using the Firefox "Responsive design mode".
Thx for your work

**Comment by LucasVaugrente** [comment]
thanks ! it works now :)
